### ISSUE TITLE
Framerate changes not applying

### ISSUE THREAD

**Issue by edgarmcbee** [WowzaMediaSystems/webrtc-examples#11]
constraintsChanged doesn't seem to switch to true when frame rate changes.

Frame rate changes do apply when a different resolution is chosen.

**Comment by edgarmcbee** [comment]
Frame rate passed through query parameters is ignored and defaults to 30, the field populates correctly though.

**Comment by akeller** [comment]
Hey there! WebRTC uses variable frame rate, so this isn't really a bug, but it is a little misleading. I believe on previous version of a similar page we put some language in about this and we are looking to get that back in to help set the expectation that it's variable.

**Comment by edgarmcbee** [comment]
Could we not apply constraints on change similar to changing the video resolution?

**Comment by akeller** [comment]
Unfortunately not in the way we are handling it. We don't fail or apply strict enforcement of frame rates.

**Comment by edgarmcbee** [comment]
Would it make sense to remove the fps input field as it currently serves no purpose?

**Comment by akeller** [comment]
I'm not sure if this is inflight future work to handle it, but I'll bring this up with the product manager.
