### ISSUE TITLE
Not working in Firefox 77.0 (64-bit), MacOSX

### ISSUE THREAD

**Issue by skyEnrique** [WowzaMediaSystems/webrtc-examples#14]
Sample works fine in chrome, but getting error (Publish failed. Unable to connect.) in Firefox.

**Comment by akeller** [comment]
Are you using Wowza Streaming Engine or Wowza Streaming Cloud?

**Comment by akeller** [comment]
@enriquecorpusjr I'll need more info to keep this open. Can you please let me know if you are using Wowza Streaming Cloud or Wowza Streaming Engine?
