### ISSUE TITLE
screen sharing with PiP Webcam.

### ISSUE THREAD

**Issue by crsepulv** [WowzaMediaSystems/webrtc-examples#17]
**Describe the solution you'd like**
When we share the screen I would like to also send the webcam in a Picture in picture box.

**Describe alternatives you've considered**
The simply way is to create 2 connection and send 2 streams but its not efficient.

As I understand a way to make this is to create a canvas and draw the screen sharing and the PiP box on it, then send the canva's result as a video to Wowza.

**Comment by akeller** [comment]
Hi @crsepulv we are working on something that should cover this request but I do not have a date when this would be available. Right now it would be up to the developer to create with the canvas like you suggested.

**Comment by akeller** [comment]
Added via #21
