### ISSUE TITLE
Meeting example / irregular websocket error in clients

### ISSUE THREAD

**Issue by TPI79** [WowzaMediaSystems/webrtc-examples#25]
I'm currently testing the meeting example.
I have the problem of an irregular Websocket Error of the remote streams and also irregularly in the different clients.
Unfortunately I cannot find any connection why the error sometimes occurs
It would be nice if you are able to check the reason 
Find attached the console logs. (if you need more logs or settings please let me know)

New stream connecting to Wowza Streaming Engine
webrtcMeetingActions.js:14 checking add
webrtcMeetingActions.js:16 adding: 2
PeerPlayer.js:30 peer player
startPlay.js:140 Websocket Error
startPlay.js:141 Objectmessage: "Waiting for stream: 2"__proto__: Object
PeerPlayer.js:58 Objectmessage: "Websocket Error: Waiting for stream: 2"__proto__: Object
webrtcMeetingActions.js:14 checking add
webrtcMeetingActions.js:26 checking remove
webrtcMeetingActions.js:14 checking add
webrtcMeetingActions.js:26 checking remove

**Comment by Wowza-Rose** [comment]
Sorry that you are having issues @TPI79. Log and configuration reviews are only done by technical support through a support ticket. They'd be happy to assist you there to identify and fix this problem. You can submit one here, even if you are on a trial license.

https://www.wowza.com/support/open-ticket

**Comment by TPI79** [comment]
Thanks for the fast response - I created a ticket.
I'm leaving the ticket open here and if we have a solution i will document it here. Is sure to be helpful to others who have the same problem. Hope you agree

**Comment by Wowza-Rose** [comment]
Yes, that would be fantastic, thanks!

**Comment by TPI79** [comment]
The issue occurs because of my wowza Dev license. The dev license doesn't allow more than 3 incoming streams or connections. At the meeting example per user 2 connections are required.
The example works with a full license.
