### ISSUE TITLE
Cannot play LIVE streams in mobile browsers

### ISSUE THREAD

**Issue by Vis5** [WowzaMediaSystems/webrtc-examples#26]
**Describe the bug**
I cannot play LIVE streams in mobile browser. LIVE is also being streamed from mobile browser. It's working if I watch from PC when I stream from my phone and watch on my phone if I stream from PC.

**To Reproduce**
1. Create a LIVE stream from any mobile browser. I've used the latest Google Chrome.
2. Click 'Play' button on the Play page after completing the form

After the player connects, it produces the SDP in the console and immediately after that it produces this error:
```
WowzaWebRTCPlay.js:140 WowzaWebRTCPlay ERROR:
WowzaWebRTCPlay.js:141 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters for m-section with mid='video'.
```

**Expected behavior**
I expect to stream and watch the LIVE without any trouble from mobile browser.

**Are you using Wowza Streaming Cloud or Wowza Streaming Engine?**
Wowza Streaming Engine 4 Subscription Edition 4.8.5 build20200616153358

**Are you running this locally (via localhost)?**
At first, yes. Then I later tested this with https://www.wowza.com/developer/webrtc/dev-view-publish. Same result.

**Additional context**
Here is my SDP of player.
```
SDP Data: v=0
o=WowzaStreamingEngine-next 1525832477 2 IN IP4 127.0.0.1
s=-
t=0 0
a=fingerprint:sha-256 E0:F8:15:0B:EE:72:2E:D1:AA:FB:F3:7C:0B:B0:9B:FE:3C:8D:34:6F:F4:36:B1:E8:96:72:76:02:95:D1:15:E0
a=group:BUNDLE video audio
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=42801f;sprop-parameter-sets=Z0KAH9oC0ChoB4RCNQ==,aM4NiA==
a=cliprect:0,0,1280,720
a=framesize:97 720-1280
a=control:trackID=2
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:a174cfb74511f47ef33daa3fd5e0da5f
a=ice-ufrag:5f32e994
a=mid:video
a=msid:{f82c65dd-f7eb-4826-9d51-5e3e8013936f} {8dc14fd0-19d2-4360-a599-3d00a8c99d99}
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-mux
a=setup:actpass
a=ssrc:1877056441 cname:{f790c2bc-0cd0-45a2-a461-33e4d90749c2}
m=audio 9 RTP/SAVPF 96
a=rtpmap:96 OPUS/48000/2
a=control:trackID=1
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:a174cfb74511f47ef33daa3fd5e0da5f
a=ice-ufrag:5f32e994
a=mid:audio
a=msid:{f82c65dd-f7eb-4826-9d51-5e3e8013936f} {5fedca2b-80fb-4847-8449-d273b7168dbd}
a=rtcp-mux
a=setup:actpass
a=ssrc:870204950 cname:{f790c2bc-0cd0-45a2-a461-33e4d90749c2}

```

**Comment by izenoni** [comment]
This should be fixed with https://github.com/WowzaMediaSystems/webrtc-examples/pull/39
