### ISSUE TITLE
WebRTC:  Failed to parse video codecs correctly.

### ISSUE THREAD

**Issue by champsupertramp** [WowzaMediaSystems/webrtc-examples#3]
Why do i keep getting this error with your webrtc-examples in Chrome and Safari browser? Sometimes i had to click the "Start streaming" multiple times and then it will work. I'm using the latest WebRTC from this repo.

Here's the video source and transcoder settings:

**Live Stream Type** 
Adaptive bitrate

**Billing Mode** 
Pay as you go

**Delivery Protocol** 
Apple HLS

**Reduced Latency Stream** 
No 

**Source Aspect Ratio** 
16:9 (Widescreen) -- 640 x 360

**Recording** 
Yes

**Closed Captions** 
None

**Comment by champsupertramp** [comment]
Your Wowza WebRTC publisher also throws this error.  I'm using the latest Safari and Chrome browsers in MacOS.

<img width="1172" alt="Screen Shot 2020-05-16 at 8 05 58 PM" src="https://user-images.githubusercontent.com/12200688/82119395-c0a07180-97b0-11ea-860f-35fa479aab3b.png">

**Comment by champsupertramp** [comment]
Wowza WebRTC Publisher logs:

```
[Log] Sdp Data: v=0
 (index.bundle.k98vxqwb.js, line 1)
o=WowzaStreamingEngine-next 777736795 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:9f272078
a=ice-pwd:1b98c37434c20ffa66a8873147152157
a=ice-options:trickle
a=fingerprint:sha-256 C6:43:59:4F:77:FB:E1:D5:32:35:F0:C8:88:E0:16:62:C7:33:0C:2A:0E:11:30:F9:B7:F7:BB:B5:DC:DA:32:F1
a=setup:passive
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=msid:2acfd567-a23e-4b68-8cee-004aea025a68 c048e845-7f67-4052-a97a-c8b8d1cf9c50
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 x-google-min-bitrate=NaN;x-google-max-bitrate=NaN
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:111 opus/48000/2
a=fmtp:111 x-google-min-bitrate=NaN;x-google-max-bitrate=NaN
a=fmtp:111 x-google-min-bitrate=64;x-google-max-bitrate=64
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 98
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:9f272078
a=ice-pwd:1b98c37434c20ffa66a8873147152157
a=ice-options:trickle
a=fingerprint:sha-256 C6:43:59:4F:77:FB:E1:D5:32:35:F0:C8:88:E0:16:62:C7:33:0C:2A:0E:11:30:F9:B7:F7:BB:B5:DC:DA:32:F1
a=setup:passive
a=mid:1
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=msid:2acfd567-a23e-4b68-8cee-004aea025a68 8f25fd8b-706c-47f5-8acc-872e746be424
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:98 H264/90000
a=fmtp:98 x-google-min-bitrate=NaN;x-google-max-bitrate=NaN
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:98 H264/90000
a=fmtp:98 x-google-min-bitrate=NaN;x-google-max-bitrate=NaN
a=fmtp:98 x-google-min-bitrate=750;x-google-max-bitrate=750
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
```

**Comment by akeller** [comment]
Are you using Wowza Streaming Engine or Cloud? Configured for UDP or TCP? I have not had this issue, I usually run in Chrome on MacOS with Wowza Streaming Engine.

**Comment by akeller** [comment]
> Your Wowza WebRTC publisher also throws this error. I'm using the latest Safari and Chrome browsers in MacOS.
> 
> <img alt="Screen Shot 2020-05-16 at 8 05 58 PM" width="1172" src="https://user-images.githubusercontent.com/12200688/82119395-c0a07180-97b0-11ea-860f-35fa479aab3b.png">

This is not part of our repo examples.

**Comment by champsupertramp** [comment]
Hi @akeller  I'm using the Wowza Cloud Service.

Regards,

**Comment by akeller** [comment]
This is not part of our repo examples today and is a different code base than the ones available here. Please submit a support ticket for further debugging as I am not able to replicate the behavior you are seeing when using Wowza Streaming Cloud with the Publish page in Chrome.

I will also respond to your forum post as well.
