### ISSUE TITLE
[BUG] H.265/HEVC playback doesn't work with Wowza Webrtc

### ISSUE THREAD

**Issue by biviel** [WowzaMediaSystems/webrtc-examples#30]
Hi,

Chrome browser started to support H.265/HEVC decode more than a month ago, wowza webrtc library fails to play back H.265 encoded webrtc video. Ant Media has a great support already for webrtc h.265 video playback, why does it fail when trying to play Wowza Streaming Engine encoded h.265?

When mpeg dash is used, encoded with h.265/HEVC with videojs, playback works fine in chrome, but when I try wowza specific webrtc it's still failing, complaining about h.265 codec. 

Thanks for looking into!

**Comment by Wowza-Rose** [comment]
Thank you for the post and we will create a feature request for H.265 playback.

**Comment by biviel** [comment]
@Wowza-Rose , thanks! Any timeline for this feature would be really appreciated! Ant Media supports already h.265 playback in their SDK's.
