### ISSUE TITLE
Meeting page not working

### ISSUE THREAD

**Issue by ernesto-longwave** [WowzaMediaSystems/webrtc-examples#31]
**Describe the bug**
It is not possible to start an audio meeting, video meeting or audio/video meeting

**To Reproduce**
1. Go to 'https://www.wowza.com/developer/webrtc/dev-meeting'
2. Fill in the Signalling url with a vali url
3. Fill in the application and stream name fields with valid values 
4. click Join
5. an erro occurs: PeerConnection Error: Failed to parse SessionDescription. m=video 9 UDP/TLS/RTP/SAVPF Invalid value: .

**Expected behavior**
The meeting should start with no errors

**Screenshots**
see attached files

**Are you using Wowza Streaming Cloud or Wowza Streaming Engine?**
Wowza streaming Engine 4.8.21+6 build 20230125151621

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: both  chrome, safari
 - Version chrome 113.0.5672.92 (Official Build) (x86_64), safari  15.6.1 (17613.3.9.1.16)

**Are you running this locally (via localhost)?**
Nope, I'm using the web client hosted by Wowza.com (https://www.wowza.com/developer/webrtc/dev-meeting) and an Wowza Media Server running on ec2 aws instance
<img width="1656" alt="Screenshot 2023-05-24 at 13 08 52405" src="https://github.com/WowzaMediaSystems/webrtc-examples/assets/79307006/6bf01dcd-a04c-417d-98d1-581c5fd67069">
<img width="841" alt="Screenshot 2023-05-24 at 13 09 35522" src="https://github.com/WowzaMediaSystems/webrtc-examples/assets/79307006/719feb98-585f-4894-b9e9-8e1edd507c27">

**Comment by rogerlittin** [comment]
Please open a Support ticket via the [Wowza Portal](https://portal.wowza.com/account/support) and link to this issue.
In the ticket, please provide conf & logs files from the server.

**Comment by izenoni** [comment]
This should be fixed with https://github.com/WowzaMediaSystems/webrtc-examples/pull/39
