### ISSUE TITLE
the videochat has so much noise and a big acoustic echo

### ISSUE THREAD

**Issue by willsun888** [WowzaMediaSystems/webrtc-examples#5]
I build the videochat with the example code, but the videochat has so much noise and a big acoustic echo. any setting maybe wrong?

**Comment by akeller** [comment]
Are you running both on same computer? While you can do this for testing purposes, you should try with headphones to reduce background noise and feedback. When testing I have not experienced this myself.

**Comment by willsun888** [comment]
I meet an issue(https://github.com/WowzaMediaSystems/webrtc-examples/issues/4), it makes the remote screen black. I solve the problem by changing the profile-level-id in sdp from 64C01E to 42C01F. But it have the noise and big acoustic echo now. Does it have anything to do with my change?  maybe profile-level-id affects the sound?   by the way,  I run the demo on two computers

**Comment by akeller** [comment]
Are sides of the conversation wearing headphones? You might be hearing reverb from the computer's audio being picked up by the microphone.

**Comment by akeller** [comment]
You can also try to mute the player element - 

`<video id="myVideoElement" autoplay playsinline muted></video>`

**Comment by akeller** [comment]
Is this still an ongoing issue? If so, I would recommend creating a support ticket.
