### ISSUE TITLE
only allowed user need to publish and play URL

### ISSUE THREAD

**Issue by BirenNegi** [WowzaMediaSystems/webrtc-examples#6]
anyone can published and play the URL, Sentax is same for everyone, **`wss://123456.streamlock.net/webrtc-session.json`** like this 
it's posible to make it secure

**Comment by akeller** [comment]
These are examples, not production ready code, so we would recommend looking into WebRTC security practices to see what best fits your use case and workflow.

We do have some guidance around WebRTC session management - https://www.wowza.com/docs/manage-webrtc-sessions-in-wowza-streaming-engine
