### ISSUE TITLE
Chrome Play example not working - Wowza hosted example does

### ISSUE THREAD

**Issue by rmgroth** [WowzaMediaSystems/webrtc-examples#7]
The Chrome Play example is giving: 

DOMException: Failed to set remote offer sdp: Failed to set remote video description send parameters.

Exact same stream plays fine at: https://www.wowza.com/developer/webrtc/dev-view-play

Trying to put together a simple player page for a project and was hoping to modify this example slightly to eliminate the need for inputs of signaling url/app/stream

**Comment by akeller** [comment]
What does your SDP offer look like? Did you setup the basic WebRTC example and build from there?

The source code on the dev-view-play is not the same as the code available in this repo today.

**Comment by rmgroth** [comment]
Resuling SDP: v=0
o=WowzaStreamingEngine-next 1074546236 2 IN IP4 127.0.0.1
s=-
t=0 0
a=fingerprint:sha-256 00:15:74:7C:F8:45:CB:AD:E9:5A:9B:D8:EA:7D:96:BA:1E:C3:21:3F:3E:26:6A:86:F6:39:11:3D:1F:D3:73:C5
a=group:BUNDLE video audio
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=4D401F;sprop-parameter-sets=Z01AH5WgFAFuwEQAAA+kAAOpgj0qgA==,aO48gA==
a=cliprect:0,0,720,1280
a=framesize:97 1280-720
a=framerate:29.97
a=control:trackID=2
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:a759f4648dd3586b9c43b108347f38fc
a=ice-ufrag:bb6d2e78
a=mid:video
a=msid:{c7854de5-40ae-4d21-a0a3-45bccad00c49} {e387c12f-15f7-4059-98cb-d378e98154f0}
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-mux
a=setup:actpass
a=ssrc:2119703255 cname:{25da1f86-eeb5-45c2-b784-3a66629e6933}
m=audio 9 RTP/SAVPF 96
a=rtpmap:96 OPUS/48000/2
a=control:trackID=1
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:a759f4648dd3586b9c43b108347f38fc
a=ice-ufrag:bb6d2e78
a=mid:audio
a=msid:{c7854de5-40ae-4d21-a0a3-45bccad00c49} {20dcc495-44df-4b2b-9082-eb4ab258e8a5}
a=rtcp-mux
a=setup:actpass
a=ssrc:469385660 cname:{25da1f86-eeb5-45c2-b784-3a66629e6933}

webrtc.js:352 DOMException: Failed to set remote offer sdp: Failed to set remote video description send parameters.

This is a straight clone from this git without modification - plugging in same SDP Url, App Name, and Stream Name into the Wowza-hosted page plays fine

**Comment by akeller** [comment]
So the good news is, we are working on releasing the hosted page code to this repo. 

The bad news is, you may still have issues running this if you do not have your SSL cert or Wowza Streaming Engine correctly configured and installed for your local machine. I'm trying to break this today to see the same error you are seeing.

**Comment by rmgroth** [comment]
That is good - we do have a LetsEncrypt cert on our instance - going to it in various browser is all green/good (this is on our production instance that we're doing this)

**Comment by akeller** [comment]
I wasn't paying close enough attention and realized you may not be doing browser-based WebRTC ingest based on this line `profile-level-id=4D401F`. In your SDP offer, you'll need to modify that to be a baseline profile accepted by the browser. My recommendation is setting `profile-level-id=42C01F`.

**Comment by akeller** [comment]
Were you able to change the `profile-level-id` and get this working?
