### ISSUE TITLE
Cannot read property 'getUserMedia' of undefined

### ISSUE THREAD

**Issue by dperber** [WowzaMediaSystems/webrtc-examples#9]
I'm checking the code and the following errors appear:

Chrome
Cannot read property 'getUserMedia' of undefined

Firefox
navigator.mediaDevices is undefined

**Comment by dperber** [comment]
Hi,

It's solved. We have to use https.

Thanks

**Comment by akeller** [comment]
Thank you for following up here!

**Comment by lrcampos97** [comment]
Thank you @dperber 

This solution worked for me!!

**Comment by ghost** [comment]
I am using python flask I have tried in all but https is not working for me

**Comment by Maunil2k** [comment]
@bhavyamverma2710 Even I'm facing the same issue , if you've found any solution could you pls post it here ?

**Comment by ghost** [comment]
@Maunil2k yes I have found
Just remove the flask and load that html, js and , CSS files in different folder.I hope that you should knwo that how to place that files .
And open folder with vscode.
Install the extension golive server
After you installed it will ask for reload.and after reloading in the very bottom in blue status bar you will see "golive" 
Open your html file in that window and press that golive and it will redirect to you to chrome and it will starting working. And if you have to use with flask change the host to 127.0.0.1 I hope this will help

**Comment by Maunil2k** [comment]
@bhavyamverma2710 Thanx, I'll work on this and post the update here.

**Comment by TiankaiHang** [comment]
Not solved...
I'm using python flask + webrtc.
If I use http directly, I will meet uncaught error with getUserMedia.
If I use https, I will get error ERR_SSL_PROTOCOL_ERROR.

**Comment by ghost** [comment]
@TiankaiHang hey you need to leave flask. Or change ip address or host to 127.0.0.1 that's all

**Comment by bluefire325** [comment]
hi im getting the microsoft edge error. how do i fix this  ihave read the documentation but idk how to apply

**Comment by Keyur-8497** [comment]
**Yes It's Working Use Https My issue Solved**.
